// Generated by `supabase gen types typescript`
// Run: pnpm gen:types (after linking Supabase project)
// This is a placeholder until the Supabase project is created.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      patients: {
        Row: {
          id: string
          clinic_id: string
          phone: string
          name: string | null
          language: string
          profile: Json
          daily_routine: Json
          sharing_enabled: boolean
          practitioner_name: string | null
          consent_at: string | null
          opted_out: boolean
          active: boolean
          auth_user_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          clinic_id?: string
          phone: string
          name?: string | null
          language?: string
          profile?: Json
          daily_routine?: Json
          sharing_enabled?: boolean
          practitioner_name?: string | null
          consent_at?: string | null
          opted_out?: boolean
          active?: boolean
          auth_user_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          phone?: string
          name?: string | null
          language?: string
          profile?: Json
          daily_routine?: Json
          sharing_enabled?: boolean
          practitioner_name?: string | null
          consent_at?: string | null
          opted_out?: boolean
          active?: boolean
          auth_user_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          patient_id: string
          role: string
          content: string
          channel: string
          media_urls: string[]
          twilio_sid: string | null
          created_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          role: string
          content: string
          channel: string
          media_urls?: string[]
          twilio_sid?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          role?: string
          content?: string
          channel?: string
          media_urls?: string[]
          twilio_sid?: string | null
          created_at?: string
        }
      }
      metrics: {
        Row: {
          id: string
          patient_id: string
          recorded_at: string
          pain_level: number | null
          discomfort: number | null
          sitting_tolerance_min: number | null
          exercises_done: string[]
          exercise_count: number
          notes: string | null
          source_message_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          recorded_at?: string
          pain_level?: number | null
          discomfort?: number | null
          sitting_tolerance_min?: number | null
          exercises_done?: string[]
          exercise_count?: number
          notes?: string | null
          source_message_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          recorded_at?: string
          pain_level?: number | null
          discomfort?: number | null
          sitting_tolerance_min?: number | null
          exercises_done?: string[]
          exercise_count?: number
          notes?: string | null
          source_message_id?: string | null
          created_at?: string
        }
      }
      reports: {
        Row: {
          id: string
          patient_id: string
          week_start: string
          summary: string | null
          metrics_summary: Json
          insights: string[]
          token: string
          created_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          week_start: string
          summary?: string | null
          metrics_summary?: Json
          insights?: string[]
          token: string
          created_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          week_start?: string
          summary?: string | null
          metrics_summary?: Json
          insights?: string[]
          token?: string
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
